# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9273a99493148fcbe2e624e62c4d2434eeb63f2818fec1897ccf235e0d32eac93434458a79b9dad02b353caabbe5f6809a18628981f67b4528fbc54c9fd9f9ec

test:
  secret_key_base: 0ee62c5128bca7cd86c3fc3ed187bbdf1f7c96e7c5a3a319b7b1ccd39ad9a4a6563204923034063e6664848c9aae6efb15ea83bf7d63e2766ecba3dc5d684cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
